repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/navhealth/git-hooks
    rev: v0.2.0
    hooks:
      - id: circleci-config-validate
      - id: circleci-orb-validate
